lang: en
messages:
  en:
    noplotworld: This is not a plot world
    noplot: You are not on a plot
    resettime: Time reinitialised on plot
    resetweather: Weather reinitialised on plot
    setrain: Rain set on plot
    settime: Time set on plot
    badargument: Bad argument. /pp to see the syntax
    notyourplot: This is not your plot
    nopermission: You don't have permission to use this command
    badtime: Time must be between 1 and 24000
    belongto: This plot belong to
  fr:
    noplotworld: Ce n'est pas un Plotworld
    noplot: Vous n'etes pas sur un plot
    resettime: Heure reinitialisee sur le plot
    resetweather: Meteo reinitialisee sur le plot
    setrain: Pluie programmee plot
    settime: Heure definie sur le plot
    badargument: Mauvais argument. /pp pour voir la syntaxe
    notyourplot: Ce n'est pas votre plot
    nopermission: Vous n'avez pas la permission d'utiliser cette commande
    badtime: L'heure doit etre comprise entre 1 et 24000
    belongto: Ce plot appartient a