name: PlotPlus
main: fr.mrkold.plotplus.MainClass
version: 2.0.0
author: MrKold
depend: [PlotMe]
softdepend: [BarAPI, PermissionsEx]
description: Change time and weather on your plot
commands:
    plotplus:
      aliases: [pp]
      description: Usage /pp weather rain | /pp time set <ticks> | /pp time reset | /pp weather reset