name: PlotPlus
main: fr.mrkold.plotplus.PlotPlusPlugin
version: '1.7'
author: MrKold
depend: [PlotMe]
softdepend: [BarAPI]
description: Change time and weather on your plot
commands:
    plotplus:
      aliases: [pp]